package io.xeros.content.achievement;

/**
 * 
 * @author Jason http://www.rune-server.org/members/jason
 * @date Mar 27, 2014
 */
public enum AchievementType {

	/*
	 * PVM
	 */
	SLAY_ANY_NPCS, SLAY_DRAGONS, SLAY_BOSSES, SLAY_DAGGANOTH_MOTHER, SLAY_NEX, SLAY_VORKATH, SLAY_ZULRAH, SLAY_HYDRA, SLAY_CERB, SLAY_KBD, SLAY_SIRE, SLAY_KRAKEN,

	SLAY_VETION, SLAY_CALLISTO, SLAY_SCORPIA, SLAY_VENENATIS, SLAY_CHAOSELE, SLAY_CHAOSFANATIC, SLAY_ARCHAEOLOGIST, SLAY_SHADOWARAPHAEL, SLAY_ARAPHAEL, SLAY_CORP, SLAY_ROCKCRAB,

	/*
	 * Skill
	 */
	FISH, COOK, MINE, SMITH, FARM, HERB, WOODCUT, FLETCH, FIRE, THIEV, AGIL, ROOFTOP, SLAY,

	/*
	 * Complete minigames/Crystal chest
	 */
	// Tier 1
	LOOT_CRYSTAL_CHEST, PEST_CONTROL_ROUNDS, FIGHT_CAVES_ROUNDS, BARROWS_KILLS, DH_KILLS, INFERNO, UNIQUE_DROPS, UPGRADE,

	/*
	 * Others
	 */
	CLUES, VOTE_CHEST_UNLOCK, TOURNAMENT,
	/*
	 * Legendary
	 */
	ARBO, TOB, COX, HESPORI, WILDY_EVENT, GROTESQUES, NIGHTMARE, HYDRA, FOE_POINTS, MIMIC, HUNLLEF, MAX, MAGE_ARENA_II,
	/*
	 * starter
	 */
	VOTER, COLLECTOR, WOGW, PRESETS, DAILY,

	/*
	* Quests
	* */

	ARK_QUEST

}
